version: '3.6'

services:
  mongo:
    image: mongo:4.4.25
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  deepstack:
    image: deepquestai/deepstack:latest
    container_name: deepstack
    environment:
      - VISION-DETECTION=True
    ports:
      - "5000:5000"
    restart: always

  web:
    image: nemethbalint/human-detector:latest
    container_name: human-detector
    expose:
      - "3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/human-detector
      - DEEPSTACK_URL=http://deepstack:5000/v1/vision/detection
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable
    restart: always

volumes:
  mongo-data:
